export const story = [
  "I'm just a little girl, so helpful and nice.",
  "Life is so fun and sweet. I'm loved and so lovely.",
  'Yet I have a little secret. I can trade my life for another.',
  "It's my dearest precious dream. To save a life, even if it costs my own.",
  'But then came the disaster. Goblins attacked us.',
  "I was too late. I couldn't save anyone.",
  'The bloodied goblin rose. He wanted my life.',
  // () => {console.log('intro fight');},
  "Oh no. I didn't mean to. Even if you killed my parents.",
  "I don't want you to die. I will save your life. I'll trade my own.",
  'But why am I a goblin now.',
  'They left me for dead.',
  'Oh no. What should I do.',
  'I must take revenge!',
  "No, I don't want to kill.",
  'You just have to save them. Like you saved me.',
  'Yes, I want to help! I want to save.',
  // () => {console.log('start game');},
];
